<Project Sdk="Aspire.AppHost.Sdk/13.2.4">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>b7019dab-4351-4d61-bed0-36746ddd638d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Banking_System.ApiService\Banking_System.ApiService.csproj" />
    <ProjectReference Include="..\Banking_System.Web\Banking_System.Web.csproj" />
  </ItemGroup>

</Project>
